backend:
  name: github
  repo: owner/repo # Replace with your GitHub username/repo
  branch: main
  base_url: http://localhost:3000 # Will be updated for production
  auth_endpoint: api/auth

# Media files will be stored in the repo under public/uploads
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  # News Updates Collection
  - name: "news"
    label: "News Updates"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Published", name: "published", widget: "boolean", default: true}

  # Blog Posts Collection  
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Published", name: "published", widget: "boolean", default: true}

  # Pages Collection
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Contact Page"
        name: "contact"
        file: "content/pages/contact.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string", required: false}
          - {label: "Address", name: "address", widget: "text", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

  # 30 Day Sprint Collection
  - name: "sprint"
    label: "30 Day Sprint"
    folder: "content/sprint"
    create: true
    slug: "day-{{day}}"
    identifier_field: "day"
    fields:
      - {label: "Day Number", name: "day", widget: "number", min: 1, max: 30}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Duration (e.g., '15 minutes')", name: "duration", widget: "string"}
      - {label: "Difficulty", name: "difficulty", widget: "select", options: ["Beginner", "Intermediate", "Advanced"]}
      - {label: "Week", name: "week", widget: "number", min: 1, max: 5}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Video URL", name: "video", widget: "string", required: false}
      - {label: "Audio URL", name: "audio", widget: "string", required: false}
      - {label: "Images", name: "images", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # Site Settings
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "content/settings/general.yml"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Site Keywords", name: "keywords", widget: "list"}
          - {label: "Site Logo", name: "logo", widget: "image", required: false}
          - {label: "Favicon", name: "favicon", widget: "image", required: false}
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - {label: "Twitter", name: "twitter", widget: "string", required: false}
              - {label: "Facebook", name: "facebook", widget: "string", required: false}
              - {label: "Instagram", name: "instagram", widget: "string", required: false}
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
              - {label: "GitHub", name: "github", widget: "string", required: false}